-- 코드를 입력하세요
SELECT 
    ANIMAL_OUTS.ANIMAL_ID, 
    ANIMAL_OUTS.ANIMAL_TYPE, 
    ANIMAL_OUTS.NAME
FROM ANIMAL_INS
INNER JOIN ANIMAL_OUTS USING (ANIMAL_ID)
WHERE 
    SEX_UPON_INTAKE LIKE 'intact%'
    AND SEX_UPON_OUTCOME NOT LIKE 'intact%'
ORDER BY ANIMAL_ID;