-- 코드를 입력하세요
SELECT 
    CATEGORY,
    PRICE AS MAX_PRICE,
    PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유') 
AND PRICE IN (
    SELECT MAX(PRICE) AS maxprice
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
)
GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC;




# SELECT 
#     FOOD_PRODUCT.CATEGORY,
#     FOOD_PRODUCT.PRICE AS MAX_PRICE,
#     FOOD_PRODUCT.PRODUCT_NAME
# FROM (
#     SELECT MAX(PRICE) FROM FOOD_PRODUCT GROUP BY CATEGORY
# ) AS maxprice
# WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
# GROUP BY CATEGORY
# ORDER BY MAX_PRICE DESC;