-- 코드를 입력하세요
SELECT 
    FOOD_PRODUCT.PRODUCT_ID, 
    PRODUCT_NAME, 
    SUM(PRICE * AMOUNT)AS TOTAL_SALES
FROM FOOD_PRODUCT
INNER JOIN FOOD_ORDER
USING (PRODUCT_ID)
WHERE DATE_FORMAT(PRODUCE_DATE,'%Y-%m')='2022-05'
GROUP BY FOOD_PRODUCT.PRODUCT_ID
ORDER BY 
    TOTAL_SALES DESC,
    PRODUCT_ID;