-- 코드를 입력하세요
SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
FROM ANIMAL_INS
INNER JOIN ANIMAL_OUTS USING (ANIMAL_ID)
WHERE TIMEDIFF(ANIMAL_OUTS.DATETIME, ANIMAL_INS.DATETIME) < 0
ORDER BY ANIMAL_INS.DATETIME